server {
    listen 7002 ssl;
    server_name api.postpin.cn;

    proxy_hide_header Access-Control-Allow-Origin;
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Authorization,token,x-requested-with' always;

    ssl_certificate "/etc/nginx/ssl/api.postpin.cn.pem";
    ssl_certificate_key "/etc/nginx/ssl/api.postpin.cn.key";
    ssl_session_timeout 10m;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.2 TLSv1.3;

    if ($request_method = OPTIONS) {
        return 204;
    }

    location /api/ {
        proxy_pass http://test:9888/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_connect_timeout 3600;
        proxy_read_timeout 3600;
    }
}
